env_id: case145
total_timesteps: 300_000
progress: true

env_cfg: configs/env.yaml
scenario_cfg: scenario/train/phaseA_line.yaml

agent_cfg: configs/agent/ppo.yaml
save_dir: artifacts/models/ppo_case145_phaseA
tb_logdir: runs/ppo_case145_phaseA
