env_id: case145
total_timesteps: 2_000_000   # give this more steps (DER is harder)
progress: true

env_cfg: configs/env.yaml
scenario_cfg: scenario/train/phaseC_der.yaml

agent_cfg: configs/agent/ppo.yaml
save_dir: artifacts/models/ppo_case145_phaseC
tb_logdir: runs/ppo_case145_phaseC

# Load Phase B weights
model_path: artifacts/models/ppo_case145_phaseB/best
